services:
  postgres_db:
    container_name: postgres_db
    image: postgres:17.6
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sh:/docker-entrypoint-initdb.d/airflow_init.sh
    networks:
      - main_network

  airflow:
    container_name: airflow
    build:
      context: ./airflow
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./extract:/opt/airflow/scripts/extract
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '999'
    networks:
      - main_network
    depends_on:
      - postgres_db
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    volumes:
      - ./dbt/safesummit:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - main_network

networks:
  main_network:
    driver: bridge