services:
  postgres_db:
    container_name: postgres_db
    image: postgres:17.6
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/